/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      parentRoute: typeof rootRoute;
    };
  }
}

/* prettier-ignore-end */

export const routeTree = rootRoute;

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": []
    }
  }
}
ROUTE_MANIFEST_END */
