/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// This file is auto-generated by TanStack Router

// Import Routes
import { Route as rootRoute } from "./routes/__root";

// No need for IndexRoute since we're only using the root route

// Populate the FileRoutesByPath interface
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree
export interface FileRoutesByFullPath {
  "/": typeof rootRoute;
}

export interface FileRoutesByTo {
  "/": typeof rootRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/";
  id: "__root__";
  fileRoutesById: FileRoutesById;
}

export const routeTree = rootRoute._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
